listener_list:
  - name: default
    bind: 0.0.0.0:25565
    motd: "Cross-Platform Server"
    default_server: paper_backend
    restricted: false
    eaglercraft_enabled: true
    eaglercraft_web_port: 8080
