listener_list:
  - name: default
    bind: 0.0.0.0:8080
    motd: "Eaglercraft Proxy"
    default_server: paper_backend
    restricted: false
    eaglercraft_enabled: true
    eaglercraft_web_port: 8080
    
