config-version = "2.7"

bind = "0.0.0.0:8080"

motd = "A Velocity Server"
show-max-players = 100

online-mode = false
force-key-authentication = false

player-info-forwarding-mode = "modern"
forwarding-secret-file = "forwarding.secret"

[servers]
lobby = "ALobby.aternos.me:43482"
lifesteal = "ALifestealServer.aternos.me:25850"
survival = "ACoolSurvivalServer.aternos.me:42361"

[forced-hosts]
