bind = "0.0.0.0:25577"

online-mode = false
player-info-forwarding-mode = "modern"
forwarding-secret-file = "forwarding.secret"

[servers]
lobby = "91.98.147.128:25873"
lifesteal = "51.222.8.7:32098"
# survival = "YOUR_SURVIVAL_IP:25565"

[forced-hosts]
"*" = ["lobby"]
